### ISSUE TITLE
`HashMap::capacity()` reported lower than the requested one

### ISSUE THREAD

**Issue by jakubadamw** [rust-lang/hashbrown#113]
My understanding of the contracts of `std::collections::HashMap` is that if a specific capacity is requested through `with_capacity()` or `reserve()`, then at no point during the lifetime of the map `capacity()` would return a quantity that's lower than the requested. This is, however, not the case in the following example:

https://github.com/jakubadamw/hashbrown-capacity-issue-test/blob/d14f5275671dbb70648b47e854cddf936661dd3a/tests/main.rs#L21-L68

where for `test_with_capacity()` I am seeing the following output:

```
---- test_with_capacity stdout ----
inserted 1988   capacity = 28
inserted 2666   capacity = 28
inserted 6040   capacity = 28
inserted 25752  capacity = 28
inserted 27146  capacity = 28
inserted 27241  capacity = 28
inserted 27242  capacity = 28
inserted 27243  capacity = 28
inserted 27285  capacity = 28
inserted 27331  capacity = 28
inserted 28712  capacity = 28
inserted 29517  capacity = 28
inserted 32582  capacity = 28
inserted 34410  capacity = 28
inserted 35690  capacity = 28
inserted 38250  capacity = 28
inserted 39274  capacity = 28
inserted 44843  capacity = 28
inserted 48680  capacity = 28
inserted 56389  capacity = 28
inserted 57394  capacity = 28
inserted 61248  capacity = 28
inserted 61510  capacity = 28
inserted 63016  capacity = 28
removed 29517   capacity = 27
thread 'test_with_capacity' panicked at 'assertion failed: `(left == right)`
  left: `28`,
 right: `27`: map.capacity() != previous_with_capacity', tests/hash_map.rs:65:5
```

28 is the initial capacity requested.

If you'd like to run the test yourself, do make sure to opt out of the `aes` target feature as the test case is based on hashes from the fallback hasher of `ahash`.

```sh
git clone https://github.com/jakubadamw/hashbrown-capacity-issue-test.git
cd hashbrown-capacity-issue-test
RUSTFLAGS="-C target-feature=-aes" cargo test
```

**Comment by Amanieu** [comment]
This is unavoidable due to the way the hash table is implemented: when an item is removed from the map, it sometimes leaves behind a tombstone. A tombstone artificially increases the load on a hash table so a rehash will occur earlier, which avoids a performance cliff when there are too many tombstones. See [this article](https://gankra.github.io/blah/hashbrown-tldr/) for details on how hashbrown works internally.

My understanding is that `with_capacity(X)` guarantees that you can insert `X` elements without reallocating, but not necessarily that this holds if you are deleting elements and inserting a total of more than `X`.

As for `capacity`, the documentation explicitly says that this is a lower bound estimate, and that the table may be able to hold more in practice.

**Comment by Amanieu** [comment]
cc @Gankro

**Comment by jakubadamw** [comment]
> This is unavoidable due to the way the hash table is implemented: when an item is removed from the map, it sometimes leaves behind a tombstone. A tombstone artificially increases the load on a hash table so a rehash will occur earlier, which avoids a performance cliff when there are too many tombstones. See [this article](https://gankra.github.io/blah/hashbrown-tldr/) for details on how hashbrown works internally.

Okay, thank you very much for the explanation. 🙂

Then I guess this can be closed.
