### ISSUE TITLE
Declare Group::static_empty()'s value as static.

### ISSUE THREAD

**Issue by rickvanprim** [rust-lang/hashbrown#115]
Presently inside of [ss2](https://github.com/rust-lang/hashbrown/blob/83ce3d5ab782dd7808394d435e7977e68f88325c/src/raw/sse2.rs#L32)/[generic.rs](https://github.com/rust-lang/hashbrown/blob/83ce3d5ab782dd7808394d435e7977e68f88325c/src/raw/generic.rs#L61), the method Group::static_empty() returns the address of a `const` value (promoted to `'static`) instead of an explicitly `static` variable.  As a result, the value ends up being created inside of each consuming dylib instead of having a singular location inside of `std`'s dylib (or hashbrown's dylib).  

In my use case, this is preventing me from reloading a dylib while any empty (`HashMap::new()`) instances exist, as their `ctrl` pointer ends up pointing to garbage in the unloaded dylib, instead of pointing to a static variable inside of `std`.

If people are cool with changing `const` -> `static`, I'd be happy to prepare the trivial PR.

**Comment by Amanieu** [comment]
The reason I defined `static_empty` as a `const` rather than a `static` is specifically so that each dylib will have its own copy, which makes `HashMap::new` slightly more efficient since it doesn't need to go through the GOT to find the address of the empty table.

However the difference is very tiny (~1 instruction in a rather cold path) so I'm OK with changing it to a `static`.

**Comment by rickvanprim** [comment]
Awesome, thanks Amanieu!  Should I create a PR tonight?
