### ISSUE TITLE
Supporting older rustc versions

### ISSUE THREAD

**Issue by mitsuhiko** [rust-lang/hashbrown#310]
I'm writing here as an indirect user of hashbrown. I'm maintaining a testing tool called insta which tries to stay compatible with old rust versions as a large part of the ecosystem tries to stay compatible with old rustc versions. Historically the version a lot of that ecosystem targeted was all the way down to 1.42. As of recently part of my dependency tree moved up to 1.46 because `serde_yaml` had to move up as `indexmap` moved up (https://github.com/bluss/indexmap/issues/214).

I opened an issue there to figure out what the lower bound is and the answer was that the lower bound is the one of hashbrown. The new release of hashbrown is likely going to bump this up all the way to `1.56` which is significantly too new.

This puts me into the situation where I have to consider which approach I can take. This is why my ask here is largely if there is a change that hashbrown can support older rustc versions considering it's such a popular dependency on a lot of code.

**Comment by Amanieu** [comment]
If you need support for an older rustc version, I have happy to accept a PR to support it and add that version to CI. However this is not something that I would do myself.

The reasoning for this is based on the Rust 2020 survey results which [showed](https://blog.rust-lang.org/2020/12/16/rust-survey-2020.html#stability) that the vast majority of users are using the latest stable version of Rust, so it makes little sense to spend effort supporting older releases. In the worst case, users which require an older release can always pin to older crate versions.

**Comment by mitsuhiko** [comment]
Yeah you're not wrong that many people are using latest rust, but there is a significant chunk of the ecosystem which has or wants to support older versions. A good idea of what the current state of affairs is for version support is the [lib.rs breakdown](https://lib.rs/stats) which at the moment looks like this:

<img width="829" alt="image" src="https://user-images.githubusercontent.com/7396/151228910-e4fbdf9a-f1c7-4bc6-9778-b53d9ec61ff1.png">

I think if there is willingness to support older versions then it should be possible to find the necessary support for it.

**Comment by Amanieu** [comment]
In the graph you can see sharp drops around Rust 1.31 and 1.56. These are the Rust releases which introduced the 2018 and 2021 editions respectively. I think it is reasonable to use 1.56 as a "baseline" for long-term support, at least until the next edition is available.

**Comment by mitsuhiko** [comment]
I believe 1.56 will be an obvious baseline in the foreseeable future, but I believe we're not at that point yet. That said, I don't know how big the pain is out there for others. I opened an issue in serde-yaml about it. Maybe it turns out that supporting serde-yaml to older Rust versions is not planned either in which case I need to look at alternatives regardless.

**Comment by mitsuhiko** [comment]
Seems like serde-yaml is not planning on supporting older Rust versions at which point I need to evaluate alternatives anyways so this can be closed.

**Comment by luke-biel** [comment]
I'd like to add my 5 cents as an indirect user of `hashbrown` through `insta` in `test-case`. We are performing currently maintenance work (https://github.com/frondeus/test-case/pull/85) on old release (from 3 months ago) and apparently our tests no longer pass. 

Bumping MSRV caused a breaking change, because our lock to insta `1.7` wasn't enough to guarantee that the code will work. I understand the desire to push forward with rust versions, but we should consider problems caused by this kind of approach. At work I used to work with rust ~1/1.5 years old. We upgraded rarely as we had to throughly test our applications for performance drops. Finding an error due to an undesired MSRV bump was inconvinient, required us to look through dependencies and spend time on undesired tasks.

I'm fan of more strict approach to semver, where user feels safe given lock on selected major version. If we want to get rust adopted by enterprise users this is something we should seek. (that's an opinion)

**Comment by Amanieu** [comment]
I'd just like to point out that hashbrown *did* make a major version bump when changing the MSRV (0.11.2 -> 0.12.0).

**Comment by luke-biel** [comment]
Yes, you are right. It may be the case that I mistargeted the place where I should mention my thoughts. It seemed convinient, as this thread is at the core of changes that caused our preblems and I completly forgot about 0.x period where MINOR means breaking changes.

I'm sorry if that was taken as an offence. I'm gonna move my call for keeping strictier MAJOR compatibility somewhere where it's more suiting  :)

**Comment by mitsuhiko** [comment]
@luke-biel which version of hashbrown are you using now and how was it pulled in? `indexmap` / `insta` / `serde_yaml` should not _yet_ be pulling in `hashbrown` 0.12.

**Comment by luke-biel** [comment]
Currently it's 0.11.2, so 1.49 rustc dependency. As I have mentioned I may have caused a confusion by choosing wrong place to report this.

My issue is that we're guaranteeing MSRV 1.41 in test-case and there are tests to validate compatibility. Due to rapid increments of MSRV in `indexmap` without bumping it's MAJOR our tests now fail.

It's only tests but can't deny that's it's a bit inconvinient. I found this thread and rushed a bit with conclusion forgetting that 0.x -> 0.y is MAJOR bump. I think `indexmap` is a better place to talk about this.

That being said I started development of 2.0 version of test-case. I have picked 1.49 as new stable MSRV. If I release crate under that and in meantime dependency on hashbrown will get bumped to 0.12 I'll have failing tests all over again.
