### ISSUE TITLE
API for removing by key hash and value

### ISSUE THREAD

**Issue by qrnch-jan** [rust-lang/hashbrown#330]
Would it be possible to add a function that allows an entry to be remove based on a key hash and a closure, sort of like how `RawEntryBuilder::from_hash()` works?

I'm having some trouble with a piece of code that uses a stored key hash to manipulate a `HashMap`.  Simplified, I need to remove an entry from a `HashMap`, but I do not have access to the entry's key.  However, I do have access to its hash and its value (which is uniquely identifiable).  Something like this would be _perfect_:

```
map.remove_by_hash(key_hash, |_k, v| {
   *v == the_value_i_am_looking_for
});
```

I run into trouble if I try to translate the key hash to a key reference by via `raw_entry()`, then `from_hash()`, and finally use the regular `remove()` method because the returned reference to the key will disallow mutable access to the `HashMap`.

**Comment by Amanieu** [comment]
Since you're using `HashMap` in non-standard ways, have you considered just using `RawTable` directly? It provides a much better interface for dealing with custom hashmaps.

I'm hesitant to add yet another extension to the `HashMap` API since it is already quite bloated. Also the libs team consensus on `RawEntry` is that it's unlikely to ever be stabilized and may be removed in the future.

**Comment by qrnch-jan** [comment]
The vast majority of what I do is plain `HashMap` stuff.  Using the `RawTable` would mean I would need to duplicate a lot of standard functionality, which I'd like to avoid.

I would prefer to make a convincing argument for accepting my pull request, but I'd be lying if I said I didn't understand the argument for removing `RawEntry`..

**Comment by qrnch-jan** [comment]
Update: I'm going the `RawTable` as suggested, no need for the `remove_by_hash()` method.
