### ISSUE TITLE
Unsound usages of unsafe implementation from `usize` to `T`

### ISSUE THREAD

**Issue by llooFlashooll** [rust-lang/hashbrown#526]
Hi, I am scanning the hashbrown in the latest version with my own static analyzer tool.

Unsafe conversion found at: src/raw/mod.rs:65:14: 65:40
``` rust
fn invalid_mut<T>(addr: usize) -> *mut T {
    unsafe { core::mem::transmute(addr) }
}
```

This unsound implementation would create a misalignment issues. The `usize` and `T` are different types.

The problematic value is further manipulated at: src/raw/mod.rs:380:13: 380:35, src/raw/mod.rs:564:13: 564:61

This would potentially cause [undefined behaviors](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) in Rust. If we further manipulate the problematic converted types, it would potentially lead to different consequences. I am reporting this issue for your attention.

**Comment by Amanieu** [comment]
This function is not unsound: it is converting an integer to a raw pointer, which is not a problem. Raw pointers are allowed to hold any address, even misaligned ones.

**Comment by taiki-e** [comment]
> The `usize` and `T` are different types.

The conversion here is `usize` to `*mut T` (pointer to `T`), **not** `usize` to `T`.
It is always sound as long as the resulting pointer is not dereferenced.

**Comment by taiki-e** [comment]
Dereferencing pointers require unsafe code, and the user must guarantee the safety of the dereference at that point.

And since invalid_mut is a private function, there is no possibility for users to use it.

See also [std::ptr::without_provenance_mut](https://doc.rust-lang.org/nightly/std/ptr/fn.without_provenance_mut.html) doing the same as invalid_mut.

**Comment by taiki-e** [comment]
> I think it is still an unsafe operation to convert the types.

"unsafe" and "unsound" are not equivalent. A code that misuses an unsafe operation is unsound, but a code that uses it correctly is sound.

That transmute is an unsafe operation has already been explained by the fact that it is an unsafe function, and invalid_mut is sound because it uses that unsafe operation in the correct way. (And since its soundness is independent of its input, it can be declared as a safe function.)
